// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6LkZYfzB8FET2itu3G6dbgSKDCNCII1Y',
    appId: '1:562363790783:web:9f6f4c1138e40c066d5d0a',
    messagingSenderId: '562363790783',
    projectId: 'final-9a48f',
    authDomain: 'final-9a48f.firebaseapp.com',
    storageBucket: 'final-9a48f.appspot.com',
    measurementId: 'G-RXMWL1EKPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2xO0WobECX20g8u3gf2MSlIKcf3kKg2k',
    appId: '1:562363790783:android:20477b1470509ba96d5d0a',
    messagingSenderId: '562363790783',
    projectId: 'final-9a48f',
    storageBucket: 'final-9a48f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6LkZYfzB8FET2itu3G6dbgSKDCNCII1Y',
    appId: '1:562363790783:web:934511963e8ed3186d5d0a',
    messagingSenderId: '562363790783',
    projectId: 'final-9a48f',
    authDomain: 'final-9a48f.firebaseapp.com',
    storageBucket: 'final-9a48f.appspot.com',
    measurementId: 'G-RED2XDMZ44',
  );
}
